package ledger

const (
	ID_COLUMN      = 0
	DATE_COLUMN    = 1
	SOURCE_COLUMN  = 2
	PERSON_COLUMN  = 3
	MEMO_COLUMN    = 4
	VALUE_COLUMN   = 5
	TYPE_COLUMN    = 6
	BALANCE_COLUMN = 7
	LABEL_COLUMN   = 8
	NOTES_COLUMN   = 9
)
